## src/Blogger/BlogBundle/Resources/config/routing.yml
#blogger_blog_homepage: # <- The name of the route, referenced in application
#    path: /hello/{name} # <- The path that is matched {denotes parameter}
#    defaults: { _controller: BloggerBlogBundle:Default:index }
#    # The controller and action that is executed
#    # In this case the controller action DefaultController::indexAction
#    # from the BloggerBlogBundle bundle
blogger_index:
  path: /
  defaults: { _controller: BloggerBlogBundle:Page:index }
  requirements:
    _method: GET

blogger_about:
  path: /about
  defaults: { _controller: BloggerBlogBundle:Page:about }
  requirements:
    _method: GET

blogger_hello:
  path: /hello/you
  defaults: { _controller: BloggerBlogBundle:Page:hello }
  requirements:
    _method: GET